In [1]:
# statement to inport numpy library
import numpy as np


In [2]:
prime_array=np.array([1,2,3,4,5])

In [3]:
print(prime_array)

[1 2 3 4 5]


In [4]:
type(prime_array)

numpy.ndarray

In [11]:
another_array=np.array([[1,2],[3,4]])

In [9]:
print(another_array)

[[1 2]
 [3 4]]


In [14]:
three_dimention_array=np.array([[1,2,3],[3,4,6],[5,6,6]])

In [15]:
print(three_dimention_array)

[[1 2 3]
 [3 4 6]
 [5 6 6]]
